// !!! This is a file automatically generated by hipify!!!
#ifndef COMMON_H
#define COMMON_H

#include <hip/hip_runtime.h>
#include <iostream>
#include <ATen/hip/HIPContext.h>

#define CUDA_CHECK(call) do { \
  hipError_t err = call; \
  if(err != hipSuccess) { \
      std::cerr << "CUDA error at " << __FILE__ << ":" << __LINE__ \
                << " code=" << err << " \"" << hipGetErrorString(err) << "\"\n"; \
      exit(1); \
  } \
} while(0)

// Kernel for vector addition.
__global__ void vectorAddKernel(float* a, const float* b, int64_t n);

// Function to launch the kernel.
void vectorAdd(float* a, const float* b, int64_t n, hipStream_t stream);

#endif // COMMON_H
