// !!! This is a file automatically generated by hipify!!!
// #include <torch/extension.h>
// #include <torch/torch.h
#include <cassert>
#include <cmath>

#include "all_gather.h"
#include "all_reduce.h"
#include "common_hip.h"
#include "reduce_scatter.h"


// Performs an all-reduce on GPU tensors via recursive-halving reduce-scatter followed by recursive-doubling all-gather.
//  - output: CUDA device pointer where the final gathered tensor will be stored.
//  - input: CUDA device pointer to the local block of size block_size.
//  - total_elems: total number of elements in output (P * block_size).
//  - buf: main working buffer for the algorithm
//  - recv_buf: buffer to receive data before it is processed
//  - comm: MPI communicator (default MPI_COMM_WORLD).
void recursiveHalvingDoublingAllReduceGPU(float* output,
                                const float* input,
                                int total_elems,
                                float* buf,                 // Same as input size
                                float* recv_buf,            // Same as input size
                                float* recv_buf2,           // Same as input size
                                float* intermediate_buf,    // Input size / world size
                                MPI_Comm comm) {
    auto stream = at::hip::getCurrentHIPStreamMasqueradingAsCUDA();
    recursiveHalvingReduceScatterGPU(intermediate_buf, input, total_elems, buf, recv_buf, comm);
    recursiveDoublingAllGatherGPU(output, intermediate_buf, total_elems, recv_buf2, comm);
    CUDA_CHECK(hipStreamSynchronize(stream));

}