// !!! This is a file automatically generated by hipify!!!
// #include <torch/extension.h>
// #include <torch/torch.h>
#include <cassert>
#include <cmath>

#include "all_gather.h"
#include "common_hip.h"


// Performs a recursive doubling all-gather on GPU tensors.
//  - output: CUDA device pointer where the final gathered tensor will be stored.
//  - input: CUDA device pointer to the local block of size block_size.
//  - total_elems: total number of elements in output (P * block_size).
//  - comm: MPI communicator (default MPI_COMM_WORLD).
void recursiveDoublingAllGatherGPU(void* output, 
                                  const void* input, 
                                  int total_elems, 
                                  void* recv_buf,  // Same as output size
                                  MPI_Comm comm) {
    
    int rank, size;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &size);

    assert(total_elems % size == 0 && "Input tensor size must be divisible by number of processes");
    int block_size = total_elems / size;

    auto stream = at::hip::getCurrentHIPStreamMasqueradingAsCUDA();

    // Copy local input into its designated block in the output buffer.
    CUDA_CHECK(hipMemcpyAsync(static_cast<char*>(output) + rank * block_size, 
                             input, 
                             block_size, 
                             hipMemcpyDeviceToDevice, 
                             stream));

    hipEvent_t stream_sync_event;
    CUDA_CHECK(hipEventCreateWithFlags(&stream_sync_event, hipEventDisableTiming));

    int seg_size = 1;  // Start with local block.
    while (seg_size < size) {
        int partner = rank ^ seg_size;
        int group_start = (rank / (2 * seg_size)) * (2 * seg_size);
        int send_offset, recv_offset;
        
        if (rank < partner) {
            send_offset = group_start * block_size;
            recv_offset = (group_start + seg_size) * block_size;
        } else {
            send_offset = (group_start + seg_size) * block_size;
            recv_offset = group_start * block_size;
        }

        int count = seg_size * block_size;
        
        // Record an event on the cuda stream.
        CUDA_CHECK(hipEventRecord(stream_sync_event, stream));
        // Wait for the copy to complete.
        CUDA_CHECK(hipEventSynchronize(stream_sync_event));
        
        MPI_Sendrecv(static_cast<char*>(output) + send_offset, count, MPI_BYTE, partner, 0,
                     static_cast<char*>(output) + recv_offset, count, MPI_BYTE, partner, 0,
                     comm, MPI_STATUS_IGNORE);
        
        seg_size *= 2;
    }
    
    CUDA_CHECK(hipEventDestroy(stream_sync_event));
}

void ringAllGatherGPU(void* output,
                      const void* input,
                      int total_elems,
                      MPI_Comm comm) {
    int rank, size;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &size);
    
    assert(total_elems % size == 0 && "Input tensor size must be divisible by number of processes");
    int block_size = total_elems / size;
    // printf("[Rank %d] block_size = %d\n", rank, block_size);

    auto stream = at::hip::getCurrentHIPStreamMasqueradingAsCUDA();
    hipEvent_t stream_sync_event;

    // Copy local input into its designated block in the output buffer.
    CUDA_CHECK(hipMemcpyAsync(static_cast<char*>(output) + rank * block_size, 
                             input, 
                             block_size, 
                             hipMemcpyDeviceToDevice, 
                             stream));

    CUDA_CHECK(hipEventCreateWithFlags(&stream_sync_event, hipEventDisableTiming));

    // P-1 rounds each sending N/P data (where P is num processes, N is total data size)
    for (int step = 0; step < size - 1; step++) {
        // Compute block indices
        int send_idx = (rank - step + size) % size;
        int recv_idx = (rank - step - 1 + size) % size;
        int send_peer = (rank + 1) % size;
        int recv_peer = (rank - 1 + size) % size;
        
        // Record an event on the cuda stream.
        CUDA_CHECK(hipEventRecord(stream_sync_event, stream));
        // Wait for the copy to complete.
        CUDA_CHECK(hipEventSynchronize(stream_sync_event));
        
        // Send the block to the right neighbor and receive from the left neighbor.
        MPI_Sendrecv(static_cast<char*>(output) + send_idx * block_size, block_size, MPI_BYTE, send_peer, 0,
                     static_cast<char*>(output) + recv_idx * block_size, block_size, MPI_BYTE, recv_peer, 0,
                     comm, MPI_STATUS_IGNORE);
    }

    // destroy event
    CUDA_CHECK(hipEventDestroy(stream_sync_event));
}
